// app/layout.jsx
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Navbar/Navbar";
import StatusBar from "./components/StatusBar/StatusBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* NAVBAR */}
        <Navbar activeKey="monitor" username="haidv" />
        <StatusBar />

        {/* PAGE CONTENT */}
        <main style={{ paddingTop: 0 }}>
          {children}
        </main>
      </body>
    </html>
  );
}
